### ISSUE TITLE
MPTimer crash in version 5.7.0

### ISSUE THREAD

**Issue by MikeSpelling** [mopub/mopub-ios-sdk#272]
MPTimer crash in version 5.7.0 which wasn't present in 5.6.0

#### Steps to reproduce the behavior:
Run the app, calling MoPub.sharedInstance() on the main thread once the app is active.
This in turn creates an MPConsentManager whose initialiser attempts to create newNextUpdateTimer which schedules an MPTimer)
Occasionally this works but re-running the app multiple times will mostly cause the observed crashes.

#### Evidence:
Crashes in Crashlytics and in XCode - easily debuggable.
[MPTimer scheduleNow] believes it has a valid timer but by the time it attempts to add it to its runloop it has been deallocated. The following line (MPTimer - 125) causes a bad access error as self.timer is nil:
[self.runloop addTimer:self.timer forMode:self.runLoopMode];

Stack Trace:
Thread 11: EXC_BAD_ACCESS (code=1, address=0x8)

#0	0x0000000184b350e0 in CFRunLoopAddTimer ()
#1	0x0000000107726868 in -[MPTimer scheduleNow]Pods/mopub-ios-sdk/MoPubSDK/Internal/Utility/MPTimer.m:125
#2	0x00000001076bbb00 in __38-[MPConsentManager newNextUpdateTimer]_block_invoke at Pods/mopub-ios-sdk/MoPubSDK/Internal/MPConsentManager.m:602
#3	0x00000001093251dc in _dispatch_call_block_and_release ()
#4	0x000000010932519c in _dispatch_client_callout ()
#5	0x0000000109331200 in _dispatch_queue_override_invoke ()
#6	0x00000001093367c8 in _dispatch_root_queue_drain ()
#7	0x0000000109336500 in _dispatch_worker_thread3 ()
#8	0x000000018487ffac in _pthread_wqthread ()
#9	0x000000018487fb08 in start_wqthread ()
Enqueued from com.apple.main-thread (Thread 1) Queue : com.apple.main-thread (serial)
#0	0x00000001093347cc in _dispatch_root_queue_push_override ()
#1	0x00000001076bba80 in -[MPConsentManager newNextUpdateTimer] at Pods/mopub-ios-sdk/MoPubSDK/Internal/MPConsentManager.m:596
#2	0x00000001076b7a30 in -[MPConsentManager init] at Pods/mopub-ios-sdk/MoPubSDK/Internal/MPConsentManager.m:142
#3	0x00000001076b78d0 in __33+[MPConsentManager sharedManager]_block_invoke at Pods/mopub-ios-sdk/MoPubSDK/Internal/MPConsentManager.m:126
#4	0x000000010932519c in _dispatch_client_callout ()
#5	0x0000000109325eb0 in dispatch_once_f ()
#6	0x00000001076b7870 in _dispatch_once [inlined] at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/include/dispatch/once.h:84
#7	0x00000001076b7854 in +[MPConsentManager sharedManager] at Pods/mopub-ios-sdk/MoPubSDK/Internal/MPConsentManager.m:125
#8	0x000000010766c294 in -[MoPub handlePersonalData] at Pods/mopub-ios-sdk/MoPubSDK/MoPub.m:171
#9	0x000000010766b098 in -[MoPub init] at Pods/mopub-ios-sdk/MoPubSDK/MoPub.m:50
#10	0x000000010766aff0 in __23+[MoPub sharedInstance]_block_invoke at Pods/mopub-ios-sdk/MoPubSDK/MoPub.m:41
#11	0x000000010932519c in _dispatch_client_callout ()
#12	0x0000000109325eb0 in dispatch_once_f ()
#13	0x000000010766af88 in _dispatch_once [inlined] at /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk/usr/include/dispatch/once.h:84
#14	0x000000010766af6c in +[MoPub sharedInstance] at Pods/mopub-ios-sdk/MoPubSDK/MoPub.m:40

**Comment by rbtgit** [comment]
Having the same issue. 
Quick workaround, change:
`[self.runloop addTimer:self.timer forMode:self.runLoopMode];`
to
`if ([self.timer isValid])
            [self.runloop addTimer:self.timer forMode:self.runLoopMode];`

**Comment by torodavit** [comment]
Having the same issue. :( 
When fixed it?

**Comment by chauduyphanvu1** [comment]
Hi everyone, we believe we've identified a fix for this issue. It's currently under review internally and will ship with an upcoming SDK release.

Vu Chau
MoPub SDK Team

**Comment by dataxpress** [comment]
> Quick workaround, change (in MPTimer.m):
> `[self.runloop addTimer:self.timer forMode:self.runLoopMode];`
> to
> `if ([self.timer isValid]) [self.runloop addTimer:self.timer forMode:self.runLoopMode];`

You made this change on line 125 right? If so, this workaround doesn't make sense to me because there is already a call to check `[self.timer isValid]` on line 108 of the same method. Maybe I'm mis-reading this?

**Comment by dataxpress** [comment]
> `if ([self.timer isValid]) [self.runloop addTimer:self.timer forMode:self.runLoopMode];`

@rbtgit Seems like this would only tighten up the constraints of the race condition, but not prevent it entirely, right?

**Comment by dataxpress** [comment]
It looks like `_nextUpdateTimer` in `MPConsentManager` is only ever accessed on the main thread, so this bug can probably be fixed by only calling `scheduleNow` on the main thread as well.

This is accomplished by changing line 596 of `MPConsentManager.m` from

        dispatch_async(dispatch_get_global_queue( DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{

to

       dispatch_async(dispatch_get_main_queue(), ^{

This still solves the problem of `MPConsentManager.sharedManager` being called twice in the same stack, while also preventing a race condition inside `MPTimer`.

@chauduyphanvu1  Any ETA on a new release or will it be sufficient to submit my app with this fix?

**Comment by chauduyphanvu1** [comment]
@dataxpress, no ETA on the upcoming SDK release, but the team confirmed that the workaround you suggested will suffice. Let us know if you need anything else!

**Comment by pepsin** [comment]
When will this be shipped? Integrated via your built framework. It'd be a mess to use the source code version and actually change your code!

**Comment by chauduyphanvu1** [comment]
@pepsin, this fix should be going in the upcoming SDK release. I'll post an update otherwise. Currently there's no timeline yet.

**Comment by scotthmccoy** [comment]
@chauduyphanvu1  Can you post a Cocoapod version that includes the fix?

**Comment by chauduyphanvu1** [comment]
@scotthmccoy 5.7.1 is expected to have the fix.

**Comment by pablogeek** [comment]
@chauduyphanvu1 We are having the same issue. Do we know when is this gonna be released?

**Comment by chauduyphanvu1** [comment]
@pablogeek 5.7.1

**Comment by pablogeek** [comment]
@chauduyphanvu1 
![Uploading Screenshot 2019-05-31 at 13.50.51.png…]()

**Comment by pablogeek** [comment]
@chauduyphanvu1 

<img width="536" alt="Screenshot 2019-05-31 at 13 50 51" src="https://user-images.githubusercontent.com/1773546/58704117-35657a80-83ab-11e9-8735-9afbeb6ce62d.png">

**Comment by chauduyphanvu1** [comment]
@pablogeek, 5.7.1 is not released yet. But it's coming soon! I'll let you know if that's not the case.

**Comment by AMoralesK** [comment]
Hello guys our application is crashing occasionally with `version 5.7.1`. Im testing on an iPhone 8+ with version 12.2, I attach a screenshot where we get this issue.

![Crash Mopub](https://user-images.githubusercontent.com/45642025/58840760-859f3f80-862c-11e9-96c7-8439ed119625.png)

**Comment by chauduyphanvu1** [comment]
@AMoralesK, thank you for letting us know! Could you also share the stack trace and the project you are using that reproduces the crash? If not, could you replicate the crash in our iOS sample app (available in this repository)?

**Comment by chauduyphanvu1** [comment]
@AMoralesK, could you try running the SDK again with a cleaned and rebuilt the project? Make sure you are using the new 5.7.1 SDK binary and purge any previous SDK references that might exist in your project.

**Comment by KAMIKAZEUA** [comment]
Ohmy, I've updated my game with this new SDK and got **50k crashes!**.
It's crashing at game launch! I'm losing a lot of money because of that!  

**THIS SHOULD BE FIXED NOW!** 😡

<img width="834" alt="Screen Shot" src="https://user-images.githubusercontent.com/3391456/58987668-a3190880-87e8-11e9-95fb-39f55ca120dd.png">

**Comment by chauduyphanvu1** [comment]
@KAMIKAZEUA, could you confirm which MoPub SDK version you are using?

**Comment by KAMIKAZEUA** [comment]
5.7.0

**Comment by chauduyphanvu1** [comment]
@KAMIKAZEUA, we released 5.7.1 that contains a fix for this crash. Consider updating and let us know if you still see it.

**Comment by KAMIKAZEUA** [comment]
Okay!

**Comment by KAMIKAZEUA** [comment]
Fixed. Thanks for bug and thanks for fix.

**Comment by MikeSpelling** [comment]
Thanks for the fix!

**Comment by dinghaoz** [comment]
This problem is still NOT fixed. We are using 5.7.1, and still seeing a lot of crashes. By reading through the code, we think that the root cause is that [NSRunLooop mainRunloop] is accessed on a background thread via -[MPTimer scheduleNow].

According to Apple, NSRunLoop is not thread safe. mainRunLoop should NOT be accessed on a thread other than the main. 
https://stackoverflow.com/questions/16771195/is-nsrunloop-thread-safe
https://developer.apple.com/documentation/foundation/nsrunloop

> Warning: The NSRunLoop class is generally not considered to be thread-safe and its methods should only be called within the context of the current thread. You should never try to call the methods of an NSRunLoop object running in a different thread, as doing so might cause unexpected results.

**Comment by KAMIKAZEUA** [comment]
I’m monitoring this for my game and it’s ok for me.

Of course I’m getting this crash reports from users with previous version of my game. Just hope they will update soon.

**Comment by dataxpress** [comment]
> This problem is still NOT fixed. We are using 5.7.1, and still seeing a lot of crashes. By reading through the code, we think that the root cause is that [NSRunLooop mainRunloop] is accessed on a background thread via -[MPTimer scheduleNow].
> 
> According to Apple, NSRunLoop is not thread safe. mainRunLoop should NOT be accessed on a thread other than the main.
> https://stackoverflow.com/questions/16771195/is-nsrunloop-thread-safe
> https://developer.apple.com/documentation/foundation/nsrunloop
> 
> > Warning: The NSRunLoop class is generally not considered to be thread-safe and its methods should only be called within the context of the current thread. You should never try to call the methods of an NSRunLoop object running in a different thread, as doing so might cause unexpected results.

This fix is working for me:
https://github.com/mopub/mopub-ios-sdk/issues/272#issuecomment-495777417

Note that this change was made on 5.7.0 - I have not updated to 5.7.1.
