### ISSUE TITLE
Mopub-Moat module uses UIWebView which make apps non-acceptable by Apple. Workaround and Question.

### ISSUE THREAD

**Issue by AndrewTerekhine** [mopub/mopub-ios-sdk#313]
Both Moat and Avid modules of MoPub iOS SDK inject UIWebView component, which will cause apps to be non-acceptable by Apple soon.

Apple will stop accepting submissions of apps that use UIWebView. I see you aware of the Avid module (https://github.com/mopub/mopub-ios-sdk/issues/285). But it's also used in Moat. Here is how to check that: 
cd [project_path]/Pods/
find . -type f | grep -e ".a" -e ".framework" | xargs grep -s UIWebView

Output:
Binary file ./Pods/mopub-ios-sdk/MoPubSDK/Viewability/Avid/libAvid-mopub-3.6.1.a matches
Binary file ./Pods/mopub-ios-sdk/MoPubSDK/Viewability/MOAT/MPUBMoatMobileAppKit.framework/Versions/A/MPUBMoatMobileAppKit matches

The question to the MoPub team: maybe it will be of interest for you to forward this info to Moat and also update your MoPub iOS integration documentation. App developers who use your current instructions can see their apps rejected by Apple pretty soon because of deprecated UIWebView.

MoPub SDK Version: 5.11.0

Workaround to avoid app rejection:
Don't use the following string in podfile:
#pod 'mopub-ios-sdk'

Use only the core module in podfile:
pod 'mopub-ios-sdk/Core'

**Comment by kkarunakaran** [comment]
We had the same issue. Narrowed it down to Avid framework. MOAT may have string reference but no UIWebView API reference. I was able to confirm it by uploading a build with just AVID stripped to AppStoreConnect. 

https://github.com/mopub/mopub-ios-sdk/issues/285
Also this issue has been flagged a while ago. It will be good if AVID is removed from GitHub until the issue is resolved. It is time consuming for devs to narrow down the issue.

**Comment by chauduyphanvu** [comment]
@AndrewTerekhine @kkarunakaran, for those opting out of viewability (Moat and/or IAS), we have documentation on disabling it [here](https://github.com/mopub/mopub-ios-sdk#disabling-viewability-measurement). Meanwhile, let me check with the rest of the team on what we can do to make the app submission experience easier for you all.

Vu Chau
MoPub Team

**Comment by rob-keepsafe** [comment]
FYI: Apple has updated their guidance that they will no longer allow apps that support `UIWebView` starting in December 2020. Hopefully this is addressed much sooner

**Comment by kkarunakaran** [comment]
> FYI: Apple has updated their guidance that they will no longer allow apps that support `UIWebView` starting in December 2020. Hopefully this is addressed much sooner

https://developer.apple.com/news/?id=12232019b Do you refer to this news?

**Comment by zhangferry** [comment]
@chauduyphanvu I have encountered the same problem, but I need to use native ads and I still can't remove Moat and IAS. When can I solve this problem? Do you have a plan? Thanks you so much.

**Comment by zhangferry** [comment]
@chauduyphanvu I solved this problem by setting the Podfile as
```
pod 'mopub-ios-sdk/Core', '~> 5.11.0'
pod 'mopub-ios-sdk/NativeAds', '~> 5.11.0'
```

**Comment by mahesh-khokhar** [comment]
> @chauduyphanvu I solved this problem by setting the Podfile as
> 
> ```
> pod 'mopub-ios-sdk/Core', '~> 5.11.0'
> pod 'mopub-ios-sdk/NativeAds', '~> 5.11.0'
> ```

still I m getting issue to load Interstitial ads

**Comment by chauduyphanvu** [comment]
@mahesh-khokhar, this thread doesn't contain the same issue as the one illustrated via your log messages. Please consider opening a separate issue and filling out the details, and we'll be happy to help!

**Comment by polmum** [comment]
> We had the same issue. Narrowed it down to Avid framework. MOAT may have string reference but no UIWebView API reference. I was able to confirm it by uploading a build with just AVID stripped to AppStoreConnect.
> 
> #285
> Since this issue has been flagged a while ago. It will be good if AVID is removed from GitHub until the deprecation warning is resolved. It is time consuming for devs to narrow down the issue.

We just checked, and the issue appears to be both in Avid and in Moat. We uploaded a version with Moat only, and we still got the UIWebView warning. Removing both libraries does appear to be effective.
Is there a plan on updating either of these to a version without UIWebViews? Or is opting out of viewability the only option available?

**Comment by chauduyphanvu** [comment]
@polmum, thanks for letting us know! Currently we do not have an update regarding our plan. I'll be sure to share something here as soon as I have one.

**Comment by dgaedcke** [comment]
Apple is now rejecting any NEW apps containing MoPub SDK 5.12.1 due to UIWebView being used in Avid & MOAT ... are you guys seriously leaving this ticket open without comment or fix for over a full month while your developers deal with this??  Please give us a patch or instructions to fix manually.

**Comment by damian-kolakowski** [comment]
@dgaedcke A temporary solution may be replacing _pod InMobiSDK_ with _pod 'InMobiSDK/Core'_. Not perfect but enough for app submission.

**Comment by kamranpirwani** [comment]
Same issue here on our end, apps are not able to be updated..

**Comment by chauduyphanvu** [comment]
Hi all, if you are flagged by Apple for UIWebView, you need to remove the Moat and IAS SDKs from your project, rebuild the app, and resubmit the app to the App Store. Note that this only affects new apps submitted to the App Store. Existing apps can continue receiving updates with Moat/IAS until December 2020.

To remove Moat and IAS, follow [these instructions](https://github.com/mopub/mopub-ios-sdk#disabling-viewability-measurement), and then choose “**Opting Out in a Manual Integration**” or “**Opting Out in a CocoaPods Integration**”. Opting out via a software approach is not sufficient. Once done, recompile the app project.

Of note: we are planning to release support for the IAB Tech Lab's Open Measurement SDK later this summer, at which point this issue will be resolved. Publishers negatively impacted by removing these SDKs can choose to delay updating MoPub until this release.

**Comment by kamranpirwani** [comment]
@chauduyphanvu What about all of the mopub adapters whom are also using the UIWebViews?

**Comment by chauduyphanvu** [comment]
@kamranpirwani, we have confirmed with our mediation partners that their SDKs have also removed UIWebView code. To the best of our knowledge, there have been no UIWebView rejections from Apple regarding mediation (adapters & SDKs).

Are you seeing any rejection for specific ad network SDK?

**Comment by kamranpirwani** [comment]
Binary file ./ios/Pods/AdColony/AdColony.framework/AdColony matches
Binary file ./ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/GoogleMobileAds matches
Binary file ./ios/Pods/VungleSDK-iOS/VungleSDK.framework/VungleSDK matches
Binary file ./ios/Pods/mopub-ios-sdk/MoPubSDK/Viewability/Avid/libAvid-mopub-3.6.1.a matches
Binary file ./ios/Pods/mopub-ios-sdk/MoPubSDK/Viewability/MOAT/MPUBMoatMobileAppKit.framework/Versions/A/MPUBMoatMobileAppKit matches
Binary file ./ios/Pods/mopub-ios-sdk/MoPubSDK/Viewability/MOAT/MPUBMoatMobileAppKit.framework/Versions/Current/MPUBMoatMobileAppKit matches
Binary file ./ios/Pods/mopub-ios-sdk/MoPubSDK/Viewability/MOAT/MPUBMoatMobileAppKit.framework/MPUBMoatMobileAppKit matches
Binary file ./ios/Pods/IronSourceSDK/IronSource/IronSource.framework/Versions/A/IronSource matches
Binary file ./ios/Pods/IronSourceSDK/IronSource/IronSource.framework/Versions/Current/IronSource matches
Binary file ./ios/Pods/IronSourceSDK/IronSource/IronSource.framework/IronSource matches
Binary file ./build/ios/iphoneos/Runner.app/Runner matches
Binary file ./build/ios/iphoneos/Runner.app/Frameworks/MoPub.framework/MoPub matches
Binary file ./build/ios/Release-iphoneos/FBSDKCoreKit/FBSDKCoreKit.framework.dSYM/Contents/Resources/DWARF/FBSDKCoreKit matches
Binary file ./build/ios/Release-iphoneos/flutter_email_sender/flutter_email_sender.framework.dSYM/Contents/Resources/DWARF/flutter_email_sender matches
Binary file ./build/ios/Release-iphoneos/Runner.app/Runner matches
Binary file ./build/ios/Release-iphoneos/Runner.app/Frameworks/MoPub.framework/MoPub matches
Binary file ./build/ios/Release-iphoneos/Runner.app.dSYM/Contents/Resources/DWARF/Runner matches
Binary file ./build/ios/Release-iphoneos/mopub-ios-sdk/MoPub.framework.dSYM/Contents/Resources/DWARF/MoPub matches
Binary file ./build/ios/Release-iphoneos/mopub-ios-sdk/MoPub.framework/MoPub matches
Binary file ./build/ios/Release-iphoneos/GoogleUtilities/GoogleUtilities.framework.dSYM/Contents/Resources/DWARF/GoogleUtilities matches

Please ignore the non relevant stuff, but I'm seeing a lot of the SDK's being flagged in here

**Comment by chauduyphanvu** [comment]
@kamranpirwani, could you confirm the versions of the above SDKs you have integrated in your apps?

Here is our data:

![image](https://user-images.githubusercontent.com/25616035/81736432-907d6980-9464-11ea-9fbd-41186ce38618.png)

**Comment by kamranpirwani** [comment]
I've verified I'm on or > than all of these versions using my MoPub adapters but still seeing problems for:

Binary file ./ios/Pods/AdColony/AdColony.framework/AdColony matches
Binary file ./ios/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/GoogleMobileAds matches
Binary file ./ios/Pods/VungleSDK-iOS/VungleSDK.framework/VungleSDK matches
Binary file ./ios/Pods/IronSourceSDK/IronSource/IronSource.framework/Versions/A/IronSource matches
Binary file ./ios/Pods/IronSourceSDK/IronSource/IronSource.framework/Versions/Current/IronSource matches
Binary file ./ios/Pods/IronSourceSDK/IronSource/IronSource.framework/IronSource matches
Binary file ./build/ios/Release-iphoneos/FBSDKCoreKit/FBSDKCoreKit.framework.dSYM/Contents/Resources/DWARF/FBSDKCoreKit matches
Binary file ./build/ios/Release-iphoneos/Runner.app/Runner matches
Binary file ./build/ios/Release-iphoneos/Runner.app.dSYM/Contents/Resources/DWARF/Runner matches
Binary file ./build/ios/Release-iphoneos/mopub-ios-sdk/MoPub.framework.dSYM/Contents/Resources/DWARF/MoPub matches
Binary file ./build/ios/Release-iphoneos/GoogleUtilities/GoogleUtilities.framework.dSYM/Contents/Resources/DWARF/GoogleUtilities matches

**Comment by chauduyphanvu** [comment]
@kamranpirwani, thanks for the check. We still need to know the exact adapter and mediation SDK versions you have integrated that you found UIWebView references in. We have confirmed with all ad networks that they have removed UIWebVIew from their SDKs. 

If you can share your search methodology, that would also help us confirm. Thank you!

**Comment by damian-kolakowski** [comment]
@chauduyphanvu you can use **nm** command for detection:

```
$ nm -u INMMoatMobileAppKit.framework/INMMoatMobileAppKit | grep "UIWebView"
                 U _OBJC_CLASS_$_UIWebView
                 U _OBJC_CLASS_$_INMMoatUIWebViewBridge
INMMoatMobileAppKit.framework/INMMoatMobileAppKit(INMMoatUIWebViewBridge.o):
                 U _OBJC_CLASS_$_UIWebView
$ nm -u InMobiSDK.framework/InMobiSDK | grep "UIWebView"
InMobiSDK.framework/InMobiSDK(OMIDUIWebViewJSExecutor.o):
                 U _OBJC_CLASS_$_OMIDInmobiUIWebViewJSExecutor
```

INMMoatMobileAppKit is not ok becuase it has some references to U __OBJC_CLASS_$_UIWebView_. InMobiSDK is ok.

**Comment by chauduyphanvu** [comment]
Thanks, @damian-kolakowski. InMobi is not one of our official network partners, and it looks like [INMMoatMobileAppKit](https://support.inmobi.com/monetize/ios-guidelines/) belongs to them. Could you raise this to their attention?

All of [MoPub's official network partners](https://developers.mopub.com/publishers/mediation/supported-mediation-partners/) have confirmed that they no longer use UIWebView starting with [these SDK releases](https://github.com/mopub/mopub-ios-sdk/issues/313#issuecomment-627543815). We are also [removing the Moat and IAS SDKs](https://github.com/mopub/mopub-ios-sdk/issues/313#issuecomment-627500353) in the upcoming MoPub SDK release, so this issue will be resolved at that time.

**Comment by damian-kolakowski** [comment]
@chauduyphanvu thanks for the clarification👍

**Comment by alexeyvolkov-dev** [comment]
Hello, here are my findings. 
used the following pods:
pod 'mopub-ios-sdk'
pod 'MoPub-AdMob-Adapters'
pod 'MoPub-Applovin-Adapters'
pod 'MoPub-FacebookAudienceNetwork-Adapters'

alex@Alexeys-MacBook-Pro gamep % grep -r "UIWebView" .
Binary file ./Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework-Current/GoogleMobileAds.framework/GoogleMobileAds matches
Binary file ./Pods/mopub-ios-sdk/MoPubSDK/Viewability/Avid/libAvid-mopub-3.6.1.a matches
Binary file ./Pods/mopub-ios-sdk/MoPubSDK/Viewability/MOAT/MPUBMoatMobileAppKit.framework/Versions/A/MPUBMoatMobileAppKit matches
Binary file ./Pods/mopub-ios-sdk/MoPubSDK/Viewability/MOAT/MPUBMoatMobileAppKit.framework/Versions/Current/MPUBMoatMobileAppKit matches
Binary file ./Pods/mopub-ios-sdk/MoPubSDK/Viewability/MOAT/MPUBMoatMobileAppKit.framework/MPUBMoatMobileAppKit matches

**Comment by azarovalex** [comment]
@alexeyvolkov-dev
> alex@Alexeys-MacBook-Pro gamep % grep -r "UIWebView" .

Actually, this command can't give you precise information about frameworks that uses UIWebView. In your example, you can see GoogleMobileAds library, but they've already removed UIWebView usage. Though they have a class that has a _UIWebView_ as part of the name, that won't affect AppStore acceptance, because the class doesn't actually link with actual UIWebView from UIKit and only happen to be named similarly.

**Comment by chauduyphanvu** [comment]
@alexeyvolkov-dev, this issue will be resolved in the 5.13.0 MoPub SDK, which will remove Moat and IAS SDKs. For mediation SDKs, please confirm the versions you integrated. Refer to https://github.com/mopub/mopub-ios-sdk/issues/313#issuecomment-627543815 for the versions that no longer had UIWebView.

**Comment by chauduyphanvu** [comment]
This issue is now resolved in the 5.13.0 release of the MoPub iOS SDK.

**Comment by wimbledon** [comment]
@chauduyphanvu, can we at least release a version that fixes this UIWebView issue for iOS 9.0 before dropping the support?
Please see https://github.com/CocoaPods/Specs/pull/14462

**Comment by alexeyvolkov-dev** [comment]
5.13.0 just worked for me. Uploaded my app without any UIWebView warnings from Apple. Thank you.
