### ISSUE TITLE
sdk initialization completion never invoked when consent status changes from explicit_yes to dnt so ads are not shown for that session (iOS 14 AppTrackingTransparency)

### ISSUE THREAD

**Issue by kris-skierniewski** [mopub/mopub-ios-sdk#384]
One line summary of the issue here
when consent status changes from MPConsentStatusConsented to MPConsentStatusDoNotTrack, mopub initialisation completion handler is never called and ads do not show in the app until the next launch. 

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.16.2

#### Device model and OS Version:
iPhone 11 Pro Max  14.4

#### Xcode Version:
12.4

#### Ad Unit IDs used in reproducing the issue:
not relevant

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

_user granted gdpr consent in the past so their current consent status is MPConsentStatusConsented_
1. user sees Apple's AppTrackingTransparency authorisation request and selects "Ask app not to track"
2. initializeSdkWithConfiguration:completion: is invoked

#### Expected behavior:
1. mopub initialisation finishes and the completion handler is called
2. ads can be shown

#### Observed behavior:
1. mopub initialisation never finishes and completion handler is never called
2. ads can't be shown

#### Evidence:
synchronizeConsentWithCompletion: is called twice during mopub initialization when consent status has changed from MPConsentStatusConsented to MPConsentStatusDoNotTrack

the second synchronisation request task is recognised as a duplicate and discarded, meaning that it's completion handler is never invoked, therefore the sdk initialization does not complete

the functions are called in the following order:

- setSdkWithConfiguration:completion: 
  - checkForDoNotTrackAndTransition 
    - setCurrentStatus:reason:statusWasReacquired:shouldBroadcast:
      - notifyConsentChangedTo:fromOldStatus:reason:canCollectPii:
        - handlePersonalDataOnStateChangeTo:fromOldStatus:
          - synchronizeConsentWithCompletion:
  - synchronizeConsentWithCompletion:

this may seem like an edge case however every user who previously granted GDPR consent and now denies ATT Tracking Authorisation will not see any ads at all for a whole session

I have provided the console output below:
Note _[MoPub][MoPub] SDK initialized and ready to display ads_  is missing 

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/64841676/115970535-e09cf100-a53a-11eb-8ac8-32818be2fe4e.png">

**Comment by dravyan** [comment]
@kris-skierniewski, thank you for the report. We will take a look and get back to you.

- MoPub Team

**Comment by dravyan** [comment]
@kris-skierniewski, This issue will be fixed in the next SDK release. We will update the thread once the SDK is available.

**Comment by kris-skierniewski** [comment]
@dravyan thank you! Do you know if the release is due in the next few days? Or will it probably be later than that? Thanks

**Comment by dravyan** [comment]
@kris-skierniewski,  it will not be in the next few days. I will notify once we have an estimated timeframe available.

**Comment by kris-skierniewski** [comment]
@dravyan I tried this but that just postponed the issue till the next session, the consent status is still synchronised twice the next time during MoPub SDK initialisation resulting in no ads for the duration of that session.

**Comment by freewillkr** [comment]
@dravyan When will this problem be solved?

**Comment by dravyan** [comment]
This issue has been resolved in MoPub SDK [v5.17.0](https://github.com/mopub/mopub-ios-sdk/releases/tag/5.17.0). Please update. Thanks!

**Comment by freewillkr** [comment]
@dravyan Thank you for your answer.
As you said, we updated it to Mopub SDK v5.17.0, but there is still a problem.

All the ads(advertisements) will be blocked if you do the following.
First, apply the 'AppTrackingTransparent' option in the iOS of the
provided 'Unity-sample-app' project. And change the setting to 'AppTracking Block'.

Unity 2019.4.21f1
MoPub 5.17.0 or 5.16.4
Adapter(AppLovin, UnityAds, Admob) latest version

Please refer to the attached file for the log.
[MoPub_5.17.0_Log.txt](https://github.com/mopub/mopub-ios-sdk/files/6492484/MoPub_5.17.0_Log.txt)

**Comment by dravyan** [comment]
@freewillkr, in the attached logs, I notice that the MoPub SDK initialization is completed. It could be no fill for the adunits. You can try with the [test adunits](https://github.com/mopub/mopub-unity-sdk/blob/1c19e9f65a6bbc8ffb9a2918e919e12a1e8bc080/unity-sample-app/Assets/MoPub/Sample/MoPubDemoGUI.cs#L29-L36) from the sample app to confirm. Let us know if you have any questions.

`[MoPub][MoPub] SDK initialized and ready to display ads.
	Initialized adapters:
	UnityAdsAdapterConfiguration: Adapter version 3.7.1.2, SDK version 3.7.1
	GoogleAdMobAdapterConfiguration: Adapter version 8.5.0.0, SDK version afma-sdk-i-v8.5.0
	AppLovinAdapterConfiguration: Adapter version 10.2.1.1, SDK version 10.2.1`
